baseURL = 'https://www.example.com/'
languageCode = 'en-US'
title = 'Blank Theme Template'
theme = 'hugo-blank-theme'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Archive'
    pageRef = '/posts'
    weight = 11

  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 20

  [[menus.main]]
    name = 'Github'
    url = 'https://github.com/haydenk/hugo-plain-text'
    weight = 99
    [menus.main.params]
      target = '_blank'
      rel = 'external'

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = true
